### ISSUE TITLE
Laptop check not working?

### ISSUE THREAD

**Issue by sonic84** [stevewood-tx/CasperScripts-Public#1]
Hello, I saw your post on JamfNation. Thank you for posting this, it's good to see what others are doing. 

You may consider re-writing line 125 and 127 (556 too?). As written, "IS_LAPTOP" is not evaluated in your if statement:

```
IS_LAPTOP=`/usr/sbin/system_profiler SPHardwareDataType | grep "Model Identifier" | grep "Book"`

if [[ $shortModel == "MacBook" ]]; then
```

consider using something like

```
IS_LAPTOP=`/usr/sbin/system_profiler SPHardwareDataType | grep "Model Identifier" | grep "Book" | wc -l | awk '{print $1}'`

if [[ "$IS_LAPTOP" != "0" ]]; then
```

Hope this helps!

**Comment by stevewood-tx** [comment]
Thank you for that!  I missed removing that one line of code.  I had
something similar to what you suggested in place before moving to
$shortModel.  So the IS_LAPTOP section was redundant.

I've removed it and re-pushed the code.

Thanks again!

Blessings,

Steve
