### ISSUE TITLE
script-to-fix-onedrive-file-folder-path-errors (or at least a few hints ;-)

### ISSUE THREAD

**Issue by dukechem** [stevewood-tx/CasperScripts-Public#3]
Any chance you could post at github the [script-to-fix-onedrive-file-folder-path-errors
](https://www.jamf.com/jamf-nation/discussions/22747/script-to-fix-onedrive-file-folder-path-errors)

Or at least give us a few hints or perhaps pseudo-code? -Thanks in advance!

**Comment by stevewood-tx** [comment]
I think you have the wrong repo. I do not have a script to fix OneDrive errors. Sorry.
